modLoader="javafml"
loaderVersion="[39,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=${mod_id}&loader=forge"
displayURL="${mod_homepage}"
logoFile="assets/${mod_id}/banner.png"
logoBlur=false
authors="${mod_author}"
description="${mod_desc}"
displayTest="IGNORE_SERVER_VERSION"

[modproperties."${mod_id}"]
    catalogueImageIcon="assets/${mod_id}/icon.png"
    catalogueBackground="assets/${mod_id}/background.png"

[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
